---
- hosts: web_servers
  become: "true"
  tasks: 
    - name: update apt-get(yum in centos) repository
      apt:
        name: "*"
        update_cache: "yes"

    - name: Install nginx
      apt: 
        name: "nginx"
        state: present